services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=ecommercedb;Username=tawsif;Password=postgres123
    depends_on:
      - db
    volumes:
      - ./:/app
    networks:
      - ecommerce-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=tawsif
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=ecommercedb
    ports:
      - "54357:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network

volumes:
  postgres-data:

networks:
  ecommerce-network:
    driver: bridge