services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5100:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=ecommercedb;Username=tawsif;Password=postgres123
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/obj
      - /app/bin
    networks:
      - ecommerce-network

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=tawsif
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=ecommercedb
    ports:
      - "5437:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - ecommerce-network
  

networks:
  ecommerce-network:
    driver: bridge